#-------------------------------
# General Site Settings
title: Bitwerker
description: Web Development // FileMaker Pro // Mac Support
email: ps@bitwerker.de

# Images
logo: "logo.svg"
bg-img: "siteimage.jpg"
avatar: "avatar.jpg"


# Menue Items
menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}


#-------------------------------
# About Section

blurb: <p><strong>Coding for the user. </strong>Development für das <a href="#">Mobile Web</a> und Mobile Apps mit Focus auf Benutzerfreudlichkeit und <a href="#">funktionales UX-Design</a>.</p>

# SKILL LIST Entries

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '10'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}


# WORKS SECTION - projects showcase

projects:
- {name: First One, folder: 'proj-1'}
- {name: Second, folder: 'proj-2'}
- {name: Third, folder: 'proj-3'}
- {name: Fourth, folder: 'proj-4'}
- {name: Fifth, folder: 'proj-5'}
- {name: Sixth, folder: 'proj-6'}
- {name: Seventh, folder: 'proj-7'}
- {name: Pro Eight, folder: 'proj-8'}
